### PR TITLE
Fix width for last image

### PR DESCRIPTION
**Pull request by Pavlo-Hural**
Fix width for list of images. Now it's looks like this:
image

### CODE REVIEW

**Comment by yterletskyi** [comment]
so what was the problem?

**Comment by Pavlo-Hural** [comment]
Problem was in screen width. Images in a row can't have width more than 100 dp. Last row have only 2 pictures, so their width bigger than another. I just decreased width for all images and now it's look corectly

**Comment by yterletskyi** [comment]
okay, but now these white borders between columns look not very beautiful. Maybe let's try to find a way to make every photo the maximum possible size to fit into the column (like it was before, so we don't have white borders)

**Comment by yterletskyi** [comment]
Maybe if we know that we will have 4 columns, and we know the screen width, we can find a best size for one photo?
Or maybe we can somehow make android do it automatically for us. Let's try to google it. I don't have a solution now too :)

**Review by yterletskyi — APPROVED** [review]

**Pull request merged**
